repos:
  - repo: local
    hooks:
      - id: cargo-fmt-nightly
        name: Cargo Fmt Nightly
        language: "rust"
        entry: cargo +nightly-2023-03-01 fmt
        pass_filenames: false
      - id: cargo-clippy
        name: Cargo clippy
        language: "rust"
        entry : cargo +nightly-2023-03-01 clippy --tests -- -D warnings
        pass_filenames : false